# 马尔可夫预测
**本节只讨论时齐的马尔可夫链**

- 马尔可夫链: $\{\xi_n,\ n=1,2,\cdots\}$
- 马尔可夫链性质: $P\{\xi_{n+m}|\xi_n=i,\xi_{n-1}=i_{n-1},\cdots,\xi_{1}=i_1\}=P\{\xi_{n+m}|\xi_n=i\}$
- 时齐的马尔可夫链还要满足:$P\{\xi_{n+m}|\xi_n=i\}=p_{ij}(m)$. 即上式右边与n无关. 其含义是, 系统从i到j经过m个时间间隔, 这与起始时刻无关.
- 马尔可夫链的$m$步转移矩阵: $P(m)=(p_{ij}(m))$. $m=1$时简称为转移矩阵.
- 柯尔莫哥洛夫-开普曼定理: 对 Markov Train 有: $p_{ij}(n+m)=\sum\limits_{k\in E}p_{ik}(n)p_{kj}(m)$
- 第$n$步概率分布为: $P^{(n)}=P^{(0)}P^n$
- 正则转移矩阵: 当且仅当存在正整数$k$, 使$P^k$的每一元素都是正数.
    - 正则转移矩阵具有唯一的不动向量.
    - 对于正则转移矩阵, $\lim\limits_{n\rightarrow\infty}P^{n}$每一行都趋于不动向量(遍历性).

In [59]:
# 例15.9

import numpy as np

state_num = 4
states = [4, 3, 2, 1, 4, 3, 1, 1, 2, 3,
          2, 1, 2, 3, 4, 4, 3, 3, 1, 1,
          1, 3, 3, 2, 1, 2, 2, 2, 4, 4,
          2, 3, 2, 3, 1, 1, 2, 4, 3, 1
         ]
P = np.zeros((state_num, state_num), dtype=np.int)
for i in range(len(states)-1):
    P[states[i]-1][states[i+1]-1] += 1

P = np.divide(P, np.sum(P, axis=1)[:,None])
print('得到概率估计的转移矩阵:', P, sep='\n')

print('这是一个正则转移矩阵, 它的10次幂为:',np.matrix(P)**10, sep='\n')

得到概率估计的转移矩阵:
[[0.4        0.4        0.1        0.1       ]
 [0.27272727 0.18181818 0.36363636 0.18181818]
 [0.36363636 0.36363636 0.18181818 0.09090909]
 [0.         0.14285714 0.57142857 0.28571429]]
这是一个正则转移矩阵, 它的10次幂为:
[[0.29393371 0.28893058 0.26829268 0.14884303]
 [0.29393371 0.28893058 0.26829268 0.14884303]
 [0.29393371 0.28893058 0.26829268 0.14884303]
 [0.29393371 0.28893058 0.26829268 0.14884303]]


In [69]:
# 例15.11

import numpy as np

P = np.matrix([[0.8, 0.1, 0.1],
               [0.5, 0.1, 0.4],
               [0.5, 0.3, 0.2]
              ])

p = np.matrix([0.2, 0.4, 0.4])

print(P**20)
print(p*P**20)

[[0.71428571 0.13095238 0.1547619 ]
 [0.71428571 0.13095238 0.1547619 ]
 [0.71428571 0.13095238 0.1547619 ]]
[[0.71428571 0.13095238 0.1547619 ]]
